# KiloNode - Developed by M6VPN (M6VPN@tuta.com)
# kilonode/cmake/KiloNodeHardening.cmake

include(CheckCCompilerFlag)
include(CheckLinkerFlag)

option(KILONODE_HARDENING "Enable default hardening options" OFF)
option(KILONODE_FORTIFY "Enable _FORTIFY_SOURCE where useful" OFF)
option(KILONODE_STACK_PROTECTOR "Enable stack protector" OFF)
option(KILONODE_RELRO_NOW "Enable ELF relro/now linker flags" OFF)
option(KILONODE_PIE "Build position independent executables" OFF)

function(kilonode_apply_hardening target_name)
	if(KILONODE_HARDENING)
		set(KILONODE_FORTIFY ON)
		set(KILONODE_STACK_PROTECTOR ON)
		set(KILONODE_RELRO_NOW ON)
		set(KILONODE_PIE ON)
	endif()

	if(KILONODE_FORTIFY)
		if(CMAKE_BUILD_TYPE STREQUAL "Release" OR
		    CMAKE_BUILD_TYPE STREQUAL "RelWithDebInfo")
			target_compile_definitions(${target_name} PRIVATE _FORTIFY_SOURCE=2)
		endif()
	endif()

	if(KILONODE_STACK_PROTECTOR)
		check_c_compiler_flag("-fstack-protector-strong" KN_HAS_STACK_PROTECTOR)
		if(KN_HAS_STACK_PROTECTOR)
			target_compile_options(${target_name} PRIVATE -fstack-protector-strong)
		endif()
	endif()

	if(KILONODE_PIE)
		check_c_compiler_flag("-fPIE" KN_HAS_FPIE)
		check_linker_flag(C "-pie" KN_HAS_PIE_LINK)
		if(KN_HAS_FPIE)
			target_compile_options(${target_name} PRIVATE -fPIE)
		endif()
		if(KN_HAS_PIE_LINK)
			target_link_options(${target_name} PRIVATE -pie)
		endif()
	endif()

	if(KILONODE_RELRO_NOW AND UNIX AND NOT APPLE)
		check_linker_flag(C "-Wl,-z,relro" KN_HAS_RELRO)
		check_linker_flag(C "-Wl,-z,now" KN_HAS_NOW)
		if(KN_HAS_RELRO)
			target_link_options(${target_name} PRIVATE -Wl,-z,relro)
		endif()
		if(KN_HAS_NOW)
			target_link_options(${target_name} PRIVATE -Wl,-z,now)
		endif()
	endif()
endfunction()
